### ISSUE TITLE
Implement Formatting Options

### ISSUE THREAD

**Issue by nadchif** [OSS-Enthusiasts/brackets-php-beautify#1]
**Current Status**

The PHP formatting is working well, with the fixed styles from the [src/thirdparty/php.js](https://github.com/nadchif/brackets-php-beautify/blob/master/src/thirdparty/php.js)

**Requested Feature**

Implement setting formatting options using either or both of the following:
1. A config file `phpbeautifyrc.json` within the parent folder
or
2. Add a key within `brackets.json` that stores the options. 

(Will need to further research on this)

Possible options can be:
* Style (K&R, BSD, GNU or PEAR)
* Indent (Space or Tabs)
* Remove all comments (true/false)
* Remove empty lines (true/false)
* Make long opening tag `<?php` from short one `<?` (true/false)
* Space inside brackets - `( )` (true/false)
* Space inside block brackets - `[ ]` (true/false)
* Spaces around operators - `* / + - && ||` etc (true/false)

For directions on how to contribute, check out [CONTRIBUTING.md](https://github.com/nadchif/brackets-php-beautify/blob/master/CONTRIBUTING.md)

**Comment by Shankhanil** [comment]
I want to work on this one. @nadchif  I am already taking a look

**Comment by Shankhanil** [comment]
So what I understand from the issue is that, you want a plugin/menu-option that will let me choose formatting options as mentioned above. And I am to accomplish that by a configuration file. Am I correct? @nadchif

**Comment by nadchif** [comment]
We don't necessarily need a menu, although that would be nice. What we need could be either of the following:
**A config file phpbeautifyrc.json within the parent folder**
With this approach we will need to be able to get the working folder and check for a `phpbeautifyrc.json` file, then we read the options from there. 

Or

**Add a key within brackets.json that stores the options.**
Brackets already stores options in a `. brackets.json` file. See  http://brackets.io/docs/current/modules/preferences/PreferencesBase.html.  So we could also have a section there where we have our options and we leverage the preferences base

**Comment by Shankhanil** [comment]
Yes, but how do can an user set the options? If we don't give a menu, then the user would have to manually change the config file.

**Comment by nadchif** [comment]
That's right! The user can manually set options in a `phpbeautifyrc.json` in the working directory and our plug in could would work (as we do for plug ins like eslint, git, webpack, npm etc), but you are right **a GUI menu would be very convenient** If you could implement it that way, that would be awesome 😁

**Comment by Shankhanil** [comment]
Let me try.

**Comment by Shankhanil** [comment]
I suggest inserting a `Newline_after_statement` parameter in the config file, which will insert a newline after every PHP statement. I need help with the RegEx for a PHP statement.

**Comment by Shankhanil** [comment]
@nadchif I am implementing the code to read preferences from .brackets.json file, using the PreferencesBase API. I am however having some issues regarding that. 

There is a function in PreferencesBase API that gives the value of the key from the brackets.json preference file, when called. I am trying to figure out how to write that. 
`PreferencesBase.get(...)` isn't working. 
The function is within `MemoryStorage` class of `PreferencesBase`. 
I am messing up the syntax. Can you help?

**Comment by nadchif** [comment]
> @nadchif I am implementing the code to read preferences from .brackets.json file, using the PreferencesBase API. I am however having some issues regarding that.
> 
> There is a function in PreferencesBase API that gives the value of the key from the brackets.json preference file, when called. I am trying to figure out how to write that.
> `PreferencesBase.get(...)` isn't working.
> The function is within `MemoryStorage` class of `PreferencesBase`.
> I am messing up the syntax. Can you help?

I'll need to read more on the Brackets API first 😄
