### ISSUE TITLE
It wrongly replaces double quotes with single quotes

### ISSUE THREAD

**Issue by martinmts** [OSS-Enthusiasts/brackets-php-beautify#16]
I have some linebreaks `"\n"` in the code. This extension replaces all `"\n"` with `'\n'`, which breaks my code.
I spent much time on finding the problem.

I hope this can be fixed.

Thanks!

**Comment by nadchif** [comment]
Thank you for bringing that to our attention. We will work on this issue

**Comment by PickJBennett** [comment]
I was just about to create this same issue. I'd love to be able to use this extension, but I can't until it's fixed. In my other tests, this extension is fantastic, so I hope it will be done soon. :)

**Comment by nadchif** [comment]
Thank you @martinmts and @PickJBennett once again for bringing this to our attention. This issue has now been fixed: https://github.com/OSS-Enthusiasts/brackets-php-beautify/commit/d72f2422eb17a7375034ad20ba442af671440e3f
