### ISSUE TITLE
Show Format option only in PHP files

### ISSUE THREAD

**Issue by nadchif** [OSS-Enthusiasts/brackets-php-beautify#2]
**Current Status**

The extension adds a ```Format Document (PHP-Beautify``` option in the Editor. See below:
![contextmenu](https://user-images.githubusercontent.com/47924887/79704011-7d390d00-82af-11ea-9c61-ffd27a9befa5.png)

This option is always visible and enabled for any file (PHP, CSS, HTML, txt, md, js, etc)

**Requested Feature**
Make the option to be enabled **only in PHP files**

For directions on how to contribute, check out [CONTRIBUTING.md](https://github.com/nadchif/brackets-php-beautify/blob/master/CONTRIBUTING.md)

**Comment by Shankhanil** [comment]
I was trying to work on this one. Do you have any relevant references that could help me? The biggest question is, can I get the file-type from a click event? @nadchif

**Comment by nadchif** [comment]
Here's a reference to the Brackets API 
http://brackets.io/docs/current/index.html. Try to explore it 😁 

I think we could approach it this way:
1. First get the [editor](http://brackets.io/docs/current/modules/editor/Editor.html). The editor will give us access to the current *document*. 

2. The [document](http://brackets.io/docs/current/modules/document/Document.html) will give us the *File* attribute. 

ie
```
const editor = EditorManager.getFocusedEditor();

const document = editor.document;
```
PS: I've not yet actually tried this, I'm just using my understanding from the API documentation.

**Comment by Shankhanil** [comment]
The API has so many options, it might take a while to get hands on the correct function

**Comment by Shankhanil** [comment]
I think the document.getLanguage() function from the brackets API might give us useful information regarding file type. 
Is there an api to selective display a menu option? Something like this?
` if (condition){
 display-menu-option; }`
If there is, that is exactly what we need.
