### ISSUE TITLE
Change "I" to "We" in README.md

### ISSUE THREAD

**Issue by nadchif** [OSS-Enthusiasts/brackets-php-beautify#8]
Good for first timers

CURRENT ISSUE: The file [README.md](https://github.com/OSS-Enthusiasts/brackets-php-beautify/blob/master/README.md) says "I" on the following line:
```
46. Contributions and suggestions are very welcome and wanted. I try to respond to pull requests within 48 hours. For more information see CONTRIBUTING.md
```

WHAT WE NEED: Change "I" to "We". It should end up something like this:
```
46. Contributions and suggestions are very welcome and wanted. We try to respond to pull requests within 48 hours. For more information see CONTRIBUTING.md
```

For a step by step guide on how to do this. See [CONTRIBUTING.md](https://github.com/OSS-Enthusiasts/brackets-php-beautify/blob/master/CONTRIBUTING.md)

**Comment by TurkishDelightt** [comment]
I will do this one!
